name: CI

on:
  repository_dispatch:
    types: [run-tests]
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:



      - name: Compile and test on remote device
        env:
          SSH_PASS: ${{ secrets.SSH_PASS }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.SECRET_PORT }} ${{ secrets.SECRET_IP }} >> ~/.ssh/known_hosts
          
          sshpass -p "$SSH_PASS" ssh -p ${{ secrets.SECRET_PORT }} ${{ secrets.SECRET_USER}}@${{ secrets.SECRET_IP }} << 'EOF'

      - name: Checkout tests repository
        uses: actions/checkout@v2
      - name: Update submodules
        run: |
          git submodule update --init --recursive
          cd 2024_C_AV_RPI
          if [ -n "${{ github.event.client_payload.branch }}" ]; then
            git checkout ${{ github.event.client_payload.branch }}
          elif [ -n "${{ github.event.client_payload.commit }}" ]; then
            git checkout ${{ github.event.client_payload.commit }}
          else
          git checkout main
          fi
          cd ..
          
          cd ./tests/C_AV_SIL
          

      - name: Trigger source repository workflow
        if: always()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: your-username/source-repo
          event-type: tests-completed
          client-payload: |
            {
              "status": "${{ job.status }}"
            }
          
          

