name: CI

on:
  repository_dispatch:
    types: [run-tests]
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Compile and test on remote device
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_USER}}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            # Initialize a variable to indicate if any command failed
            failed=false
            ls
            cd ./testDir
            git clone git@github.com:EPFLRocketTeam/C_AV_SIL.git
             if [ $? -ne 0 ]; then
              failed=true
            fi
            cd C_AV_SIL
            git checkout ${{ github.head_ref }}
             if [ $? -ne 0 ]; then
              failed=true
            fi
            git submodule update --init --recursive --remote
            if [ -n "${{ github.event.client_payload.branch }}" ]; then
               git submodule set-branch --branch ${{ github.event.client_payload.branch }} ./2024_C_AV_RPI/
             if [ $? -ne 0 ]; then
              failed=true
            fi
            else 
            git checkout ${{ github.head_ref }}
             if [ $? -ne 0 ]; then
              failed=true
            fi
            fi
            
            git submodule set-branch --branch reorga ./2024_C_AV_RPI/
      
            mkdir build
            cd build
            cmake ..
            make
             if [ $? -ne 0 ]; then
              failed=true
            fi
            cd ../..

            if [ "$failed" = true ]; then
              status="failure"
            else
              status="success"
            fi
            
  

      - name: Bmp test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_USER}}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            cd ./testDir/C_AV_SIL/build/tests
            sudo ./BMP390_test 
            

      - name: gps test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_USER}}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            cd ./testDir/C_AV_SIL/build/tests
            sudo ./BMP390_test 

      - name: LoRa test
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_USER}}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            cd ./testDir/C_AV_SIL/build/tests
            sudo ./BMP390_test 
      
            

      - name: Trigger source repository workflow
        if: always()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: EPFLRocketTeam/2024_C_AV_RPI
          event-type: tests-completed
          client-payload: |
            {
              "status": "${{ env.status }}"
            }
          
          

