name: CI

on:
  repository_dispatch:
    types: [run-tests]
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compile and test on remote device
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_USER}}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            # Initialize a variable to indicate if any command failed
            failed=false
            ls
            cd ./testDir
            git clone git@github.com:EPFLRocketTeam/C_AV_SIL.git
            cd C_AV_SIL
            git checkout ${{ github.head_ref }}
            git submodule update --init --recursive --remote
            if [ -n "${{ github.event.client_payload.branch }}" ]; then
              git submodule set-branch --branch ${{ github.event.client_payload.branch }} ./2024_C_AV_RPI/
              git checkout ${{ github.event.client_payload.branch }}
            else 
            git submodule set-branch --branch main ./2024_C_AV_RPI/
            fi
            

            cd 2024_C_AV_RPI
            git submodule update --init --recursive --remote
            cd ..
            #TODO: check where we are building from
            cat ./CMakeLists.txt
            mkdir build
            cd build
            cmake ..
            make
            ls
             if [ $? -ne 0 ]; then
              failed=true
            fi
            ## Add tests from here
            
            ## Add tests above
            cd ../..
            

            if [ "$failed" = true ]; then
              status="failure"
            else
              status="success"
            fi

      
            
  
  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Temp
        run: echo temp
      #- name: Bmp test
      #  uses: appleboy/ssh-action@v1.0.3
      #  with:
      #    host: ${{ secrets.SECRET_IP }}
      #    username: ${{ secrets.SECRET_USER}}
      #    password: ${{ secrets.SSH_PASS }}
      #    port: ${{ secrets.SECRET_PORT }}
      #    script: |
      #      cd ./testDir/C_AV_SIL/build/2024_C_AV_RPI
      #      ls
      #      sudo ./BMP390_test || exit 1
      #      
#
#
      #- name: gps test
      #  uses: appleboy/ssh-action@v1.0.3
      #  with:
      #    host: ${{ secrets.SECRET_IP }}
      #    username: ${{ secrets.SECRET_USER}}
      #    password: ${{ secrets.SSH_PASS }}
      #    port: ${{ secrets.SECRET_PORT }}
      #    script: |
      #      cd ./testDir/C_AV_SIL/build/2024_C_AV_RPI
      #      sudo ./BMP390_test || exit 1
#
      #- name: LoRa test
      #  uses: appleboy/ssh-action@v1.0.3
      #  with:
      #    host: ${{ secrets.SECRET_IP }}
      #    username: ${{ secrets.SECRET_USER}}
      #    password: ${{ secrets.SSH_PASS }}
      #    port: ${{ secrets.SECRET_PORT }}
      #    script: |
      #      cd ./testDir/C_AV_SIL/build/2024_C_AV_RPI
      #      sudo ./BMP390_test || exit 1
      #      
      #
#
      #- name: ADXL test
      #  uses: appleboy/ssh-action@v1.0.3
      #  with:
      #    host: ${{ secrets.SECRET_IP }}
      #    username: ${{ secrets.SECRET_USER}}
      #    password: ${{ secrets.SSH_PASS }}
      #    port: ${{ secrets.SECRET_PORT }}
      #    script: |
      #      cd ./testDir/C_AV_SIL/build/2024_C_AV_RPI
      #      sudo ./ADXL375_test || exit 1


  coverage:
    needs: tests
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Analyse coverage
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_USER}}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            cd ./testDir/C_AV_SIL/build/2024_C_AV_RPI
            find . -name "*.gcda" -exec gcov {} \;
            cd ../..
            source ~/.bashrc
            /opt/sonar-scanner/bin/sonar-scanner -Dsonar.token=${{secrets.TOKENMARIN}} -Dsonar.pullrequest.key=${{ github.event.client_payload.pull_request_number }} -Dsonar.pullrequest.branch=${{ github.event.client_payload.branch }} -Dsonar.pullrequest.base=${{ github.event.client_payload.base }} -Dsonar.pullrequest.provider=github -Dsonar.pullrequest.github.repository=EPFLRocketTeam/C_AV_SIL -Dsonar.pullrequest.github.endpoint=https://api.github.com -Dsonar.pullrequest.github.token.secured=${{secrets.GITHUB_TOKEN}} -Dsonar.cfamily.build-wrapper-output=./build/2024_C_AV_RPI -Dsonar.cfamily.cache.enabled=true -Dsonar.cfamily.cache.path=/tmp/sonar-cfamily

          
  clean:
    needs: coverage
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Clean repo
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_USER}}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            cd ./testDir
            rm -r C_AV_SIL

      
          
          

