name: CI

on:
  repository_dispatch:
    types: [run-tests]
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Compile and test on remote device
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SECRET_IP }}
          username: ${{ secrets.SECRET_USER}}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SECRET_PORT }}
          script: |
            ls
            cd ./testDir
            git clone git@github.com:EPFLRocketTeam/C_AV_SIL.git
            cd C_AV_SIL
            git checkout ${{ github.head_ref }}
            if [ -n "${{ github.event.client_payload.branch }}" ]; then
              cd 2024_C_AV_RPI
              git checkout ${{ github.event.client_payload.branch }}
            fi
            cd 2024_C_AV_RPI
            
            git checkout reorga
            cd ..
            mkdir build
            cd build
            cmake ..
            make
            cd ../..
            rm -rf C_AV_SIL
            
            

      - name: Trigger source repository workflow
        if: always()
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: your-username/source-repo
          event-type: tests-completed
          client-payload: |
            {
              "status": "${{ job.status }}"
            }
          
          

