name: am I dumb ?

on:
  repository_dispatch:
    types: [completed]

jobs:
    check-tests:
        runs-on: ubuntu-latest
        steps:
          - name: Check the status of the tests
            run: exit 1